version: '3.8'

services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "sql-db-pfe"
      MYSQL_USER: "jean"
      MYSQL_PASSWORD: "root"
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: "jean"
      PMA_PASSWORD: "root"
    ports:
      - "8080:80"
    depends_on:
      - mariadb


volumes:
  mariadb_data: