# Generated by Django 5.0.14 on 2025-07-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='sentiment_score',
        ),
        migrations.AddField(
            model_name='new',
            name='negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='new',
            name='positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='new',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
