# Generated by Django 5.0.14 on 2025-06-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cryptoinfo',
            name='market_cap_usd',
        ),
        migrations.RemoveField(
            model_name='cryptoinfo',
            name='percent_change_1h',
        ),
        migrations.RemoveField(
            model_name='cryptoinfo',
            name='percent_change_24h',
        ),
        migrations.RemoveField(
            model_name='cryptoinfo',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='cryptoinfo',
            name='price_usd',
        ),
        migrations.RemoveField(
            model_name='cryptoinfo',
            name='volume_24h',
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='ath',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='ath_change_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='ath_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='atl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='atl_change_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='atl_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='drawdown_from_ath',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='drawup_from_atl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='fully_diluted_valuation',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='high_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='low_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='market_cap_change_24h',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='market_cap_change_percentage_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='market_cap_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='price_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='price_change_percentage_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='total_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='volatility_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoinfo',
            name='circulating_supply',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoinfo',
            name='crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='core.crypto'),
        ),
        migrations.AlterField(
            model_name='cryptoinfo',
            name='max_supply',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoinfo',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoinfo',
            name='total_supply',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
