# Generated by Django 4.2.23 on 2025-08-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marketindicatorsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoinfo',
            name='current_price',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoinfo',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cryptoinfo',
            index=models.Index(fields=['crypto', 'timestamp'], name='idx_crypto_ts'),
        ),
        migrations.AddIndex(
            model_name='cryptoinfo',
            index=models.Index(fields=['crypto', 'timestamp', 'total_volume'], name='idx_crypto_ts_tv'),
        ),
        migrations.AddIndex(
            model_name='cryptoinfo',
            index=models.Index(fields=['crypto', 'timestamp', 'total_volume', 'current_price'], name='idx_crypto_ts_tv_cp'),
        ),
        migrations.AddIndex(
            model_name='cryptoinfo',
            index=models.Index(fields=['timestamp'], name='idx_ts_only'),
        ),
        migrations.AddIndex(
            model_name='cryptoinfo',
            index=models.Index(fields=['-timestamp'], name='idx_ts_desc'),
        ),
    ]
