# Generated by Django 4.2.23 on 2025-08-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cryptoinfo_current_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('uniform', 'Uniform shock'), ('factor', 'Factor shock'), ('historical', 'Historical replay')], max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('horizon_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
